//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportDirect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportDirect.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string About_us_Txt {
            get {
                return ResourceManager.GetString("About_us_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountTxt {
            get {
                return ResourceManager.GetString("AccountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressTxt {
            get {
                return ResourceManager.GetString("AddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode scan.
        /// </summary>
        internal static string Barcode_scanTxt {
            get {
                return ResourceManager.GetString("Barcode_scanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        internal static string BenefitsTxt {
            get {
                return ResourceManager.GetString("BenefitsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string BlogTxt {
            get {
                return ResourceManager.GetString("BlogTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Installation.
        /// </summary>
        internal static string Book_InstallationTxt {
            get {
                return ResourceManager.GetString("Book_InstallationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business location.
        /// </summary>
        internal static string Business_locationTxt {
            get {
                return ResourceManager.GetString("Business_locationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us On.
        /// </summary>
        internal static string CallOnUsTxt {
            get {
                return ResourceManager.GetString("CallOnUsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call:1-800-397-2795.
        /// </summary>
        internal static string callTxt {
            get {
                return ResourceManager.GetString("callTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string ComplexTxt {
            get {
                return ResourceManager.GetString("ComplexTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact_us_Txt {
            get {
                return ResourceManager.GetString("Contact_us_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContantUsBtnTxt {
            get {
                return ResourceManager.GetString("ContantUsBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string createnewaccountTxt {
            get {
                return ResourceManager.GetString("createnewaccountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddressTxt {
            get {
                return ResourceManager.GetString("EmailAddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLORE OTHER SERVICES.
        /// </summary>
        internal static string ExploreOtherSrvcsTxt {
            get {
                return ResourceManager.GetString("ExploreOtherSrvcsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ_Txt {
            get {
                return ResourceManager.GetString("FAQ_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUsTxt {
            get {
                return ResourceManager.GetString("FollowUsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        internal static string GetInTouchBtnTxt {
            get {
                return ResourceManager.GetString("GetInTouchBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStartBtnTxt {
            get {
                return ResourceManager.GetString("GetStartBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Home.
        /// </summary>
        internal static string GoToHomeTxt {
            get {
                return ResourceManager.GetString("GoToHomeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are happy to help You.
        /// </summary>
        internal static string HappyTxt {
            get {
                return ResourceManager.GetString("HappyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpTxt {
            get {
                return ResourceManager.GetString("HelpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTxt {
            get {
                return ResourceManager.GetString("HomeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know More.
        /// </summary>
        internal static string KnwMorTxt {
            get {
                return ResourceManager.GetString("KnwMorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Comment.
        /// </summary>
        internal static string LeaveCmntTxt {
            get {
                return ResourceManager.GetString("LeaveCmntTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your requirement and.
        /// </summary>
        internal static string LetKnowRqrmntTxt {
            get {
                return ResourceManager.GetString("LetKnowRqrmntTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your requirement and.
        /// </summary>
        internal static string LetUsKnoUrRqmntAndTxt {
            get {
                return ResourceManager.GetString("LetUsKnoUrRqmntAndTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live customer service.
        /// </summary>
        internal static string Live_customer_serviceTxt {
            get {
                return ResourceManager.GetString("Live_customer_serviceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutTxt {
            get {
                return ResourceManager.GetString("LogoutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the same illusion which lifts the horion of the sea to the level of the spector on a hillside, the sable cloud beneath was dished out....
        /// </summary>
        internal static string MediaBuyingExplainTxt {
            get {
                return ResourceManager.GetString("MediaBuyingExplainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Buying.
        /// </summary>
        internal static string MediaBuyingTxt {
            get {
                return ResourceManager.GetString("MediaBuyingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Buying Work.
        /// </summary>
        internal static string MediaBuyingWorkTxt {
            get {
                return ResourceManager.GetString("MediaBuyingWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member-only promotions.
        /// </summary>
        internal static string Member_only_promotionsTxt {
            get {
                return ResourceManager.GetString("Member_only_promotionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS &amp;amp; BLOGS.
        /// </summary>
        internal static string NewsBlogsTxt {
            get {
                return ResourceManager.GetString("NewsBlogsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsTxt {
            get {
                return ResourceManager.GetString("NewsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string OffersTxt {
            get {
                return ResourceManager.GetString("OffersTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Sale.
        /// </summary>
        internal static string On_SaleTxt {
            get {
                return ResourceManager.GetString("On_SaleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Tracking.
        /// </summary>
        internal static string Order_TrackingTxt {
            get {
                return ResourceManager.GetString("Order_TrackingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string orTxt {
            get {
                return ResourceManager.GetString("orTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Policies.
        /// </summary>
        internal static string Our_PoliciesTxt {
            get {
                return ResourceManager.GetString("Our_PoliciesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Clients.
        /// </summary>
        internal static string OurClientsTxt {
            get {
                return ResourceManager.GetString("OurClientsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR SERVICES.
        /// </summary>
        internal static string OurServicesTxt {
            get {
                return ResourceManager.GetString("OurServicesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR WORK.
        /// </summary>
        internal static string OurWorkTxt {
            get {
                return ResourceManager.GetString("OurWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized experience.
        /// </summary>
        internal static string Personalized_experienceTxt {
            get {
                return ResourceManager.GetString("Personalized_experienceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-launch access to products.
        /// </summary>
        internal static string Pre_launch_access_to_productsTxt {
            get {
                return ResourceManager.GetString("Pre-launch_access_to_productsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and security.
        /// </summary>
        internal static string Privacy_and_securityTxt {
            get {
                return ResourceManager.GetString("Privacy_and_securityTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string PromotionTxt {
            get {
                return ResourceManager.GetString("PromotionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string QuoteTxt {
            get {
                return ResourceManager.GetString("QuoteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced shipping.
        /// </summary>
        internal static string Reduced_shippingTxt {
            get {
                return ResourceManager.GetString("Reduced_shippingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer a friend.
        /// </summary>
        internal static string Refer_a_friendTxt {
            get {
                return ResourceManager.GetString("Refer_a_friendTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string SettingTxt {
            get {
                return ResourceManager.GetString("SettingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareTxt {
            get {
                return ResourceManager.GetString("ShareTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SigninTxt {
            get {
                return ResourceManager.GetString("SigninTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string SimpleTxt {
            get {
                return ResourceManager.GetString("SimpleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since 2009, every client is important to us and we would to thank our layal customers. thank you.
        /// </summary>
        internal static string Since_Txt {
            get {
                return ResourceManager.GetString("Since_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportdirect.ca Plus Memeber.
        /// </summary>
        internal static string SportdirectcaPlusMemeberTxt {
            get {
                return ResourceManager.GetString("SportdirectcaPlusMemeberTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify Technology S.A. is an international media services provider. It is legally domiciled in Luxembourg and is headquartered in Stockholm, Sweden..
        /// </summary>
        internal static string SpotifyExplainTxt {
            get {
                return ResourceManager.GetString("SpotifyExplainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify.
        /// </summary>
        internal static string SpotifyTxt {
            get {
                return ResourceManager.GetString("SpotifyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify Work.
        /// </summary>
        internal static string SpotifyWorkTxt {
            get {
                return ResourceManager.GetString("SpotifyWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtnTxt {
            get {
                return ResourceManager.GetString("SubmitBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        internal static string Terms_of_use {
            get {
                return ResourceManager.GetString("Terms_of_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string ThnkUTxt {
            get {
                return ResourceManager.GetString("ThnkUTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL.
        /// </summary>
        internal static string ViewAllTxt {
            get {
                return ResourceManager.GetString("ViewAllTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning and advice.
        /// </summary>
        internal static string Warning_and_adviceTxt {
            get {
                return ResourceManager.GetString("Warning_and_adviceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll get back you shortly.
        /// </summary>
        internal static string WeWillgetBakShrtlyTxt {
            get {
                return ResourceManager.GetString("WeWillgetBakShrtlyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we&apos;ll get back to you soon.
        /// </summary>
        internal static string WeWillGetBckToUSoonTxt {
            get {
                return ResourceManager.GetString("WeWillGetBckToUSoonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Us On.
        /// </summary>
        internal static string WriteUsOnTxt {
            get {
                return ResourceManager.GetString("WriteUsOnTxt", resourceCulture);
            }
        }
    }
}
